#
### Namespace
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE

#
### postgres
#
---
apiVersion: v1
kind: Service
metadata:
  name: plausible-postgres
  namespace: $NAMESPACE
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: plausible
  ports:
    - name: db
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: plausible-postgres
  namespace: $NAMESPACE
data:
  username: cGxhdXNpYmxl # plausible
  password: $BASE64_POSTGRES_PASSWORD
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-postgres
  namespace: $NAMESPACE
spec:
  serviceName: plausible-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: plausible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: plausible
    spec:
      restartPolicy: Always
      # https://github.com/docker-library/postgres/blob/ce5bf6e7eb8f339b2a8561bf8fb5fe5d4e8c96aa/14/alpine3.19/Dockerfile#L12
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
      containers:
        - name: plausible-postgres
          image: postgres:14
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: plausible-postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: plausible
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: password
  volumeClaimTemplates:
    - metadata:
        name: plausible-postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

#
### clickhouse
#
---
apiVersion: v1
kind: Service
metadata:
  name: plausible-clickhouse
  namespace: $NAMESPACE
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: plausible
  ports:
    - name: db
      port: 8123
      targetPort: 8123
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: plausible-clickhouse
  namespace: $NAMESPACE
data:
  username: Y2xpY2tob3VzZQ== # clickhouse
  password: $BASE64_CLICKHOUSE_PASSWORD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-clickhouse
  namespace: $NAMESPACE
data:
  clickhouse-config.xml: |
    <yandex>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>
        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
    </yandex>
  clickhouse-user-config.xml: |
    <yandex>
        <profiles>
            <default>
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
            </default>
        </profiles>
    </yandex>
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plausible-clickhouse
  namespace: $NAMESPACE
spec:
  serviceName: plausible-clickhouse
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/part-of: plausible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clickhouse
        app.kubernetes.io/part-of: plausible
    spec:
      restartPolicy: Always
      securityContext:
        # https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile.alpine#L44
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: plausible-clickhouse
          image: clickhouse/clickhouse-server:23-alpine
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: plausible-clickhouse-data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d/logging.xml
              subPath: clickhouse-config.xml
              readOnly: true
            - name: config
              mountPath: /etc/clickhouse-server/users.d/logging.xml
              subPath: clickhouse-user-config.xml
              readOnly: true
          env:
            - name: CLICKHOUSE_DB
              value: plausible
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: password
      volumes:
        - name: config
          configMap:
            name: plausible-clickhouse
  volumeClaimTemplates:
    - metadata:
        name: plausible-clickhouse-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

#
### plausible
#
---
apiVersion: v1
kind: Service
metadata:
  name: plausible
  namespace: $NAMESPACE
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: plausible
    app.kubernetes.io/part-of: plausible
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
  namespace: $NAMESPACE
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - $MANAGED_DOMAIN
      secretName: plausible-tls-certificate
  rules:
    - host: $MANAGED_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: plausible-plausible
  namespace: $NAMESPACE
data:
  secret: $BASE64_SECRET_KEY_BASE
---
apiVersion: v1
kind: Secret
metadata:
  name: plausible-smtp
  namespace: $NAMESPACE
data:
  email: $BASE64_SMTP_EMAIL
  password: $BASE64_SMTP_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible
      app.kubernetes.io/part-of: plausible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plausible
        app.kubernetes.io/part-of: plausible
    spec:
      restartPolicy: Always
      # see https://github.com/plausible/analytics/blob/master/Dockerfile
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: plausible-init
          image: plausible/analytics:v2
          securityContext:
            allowPrivilegeEscalation: false
          command:
            - "/bin/sh"
            - "-c"
          args:
            - sleep 30 && /entrypoint.sh db createdb && /entrypoint.sh db migrate
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: password
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: password
            - name: BASE_URL
              value: $BASE_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: plausible-plausible
                  key: secret
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(PLAUSIBLE_POSTGRES_SERVICE_HOST):$(PLAUSIBLE_POSTGRES_SERVICE_PORT_DB)/plausible
            - name: CLICKHOUSE_DATABASE_URL
              value: http://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@$(PLAUSIBLE_CLICKHOUSE_SERVICE_HOST):$(PLAUSIBLE_CLICKHOUSE_SERVICE_PORT_DB)/plausible
      containers:
        - name: plausible
          image: plausible/analytics:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-postgres
                  key: password
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plausible-clickhouse
                  key: password
            - name: BASE_URL
              value: $BASE_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: plausible-plausible
                  key: secret
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(PLAUSIBLE_POSTGRES_SERVICE_HOST):$(PLAUSIBLE_POSTGRES_SERVICE_PORT_DB)/plausible
            - name: CLICKHOUSE_DATABASE_URL
              value: http://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@$(PLAUSIBLE_CLICKHOUSE_SERVICE_HOST):$(PLAUSIBLE_CLICKHOUSE_SERVICE_PORT_DB)/plausible
            - name: MAILER_EMAIL
              value: $MAILER_EMAIL
            - name: SMTP_HOST_ADDR
              value: $SMTP_HOST_ADDR
            - name: SMTP_HOST_PORT
              value: "$SMTP_HOST_PORT"
            - name: SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: plausible-smtp
                  key: email
            - name: SMTP_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: plausible-smtp
                  key: password
            - name: ENABLE_EMAIL_VERIFICATION
              value: "true"
            - name: DISABLE_REGISTRATION
              value: invite_only
