name: deploy (dev)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 runtime-dev
      - run: ./deploy.sh dev
        env:
          SECRET: ${{ secrets.SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          RUNTIME_DOMAIN: ${{ vars.RUNTIME_DEV_DOMAIN }}
